# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn run build
    - name: Run the tests and generate coverage report
      run: yarn run test
      
    - name: Code Coverage Report Action
      uses: insightsengineering/coverage-action@v2.3.3
            
      
    - name: Netlify Deploy

      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GITHUB_USER_APP_SITE }}
      run: curl -X POST -d {} ${{ secrets.NETLIFY_GITHUB_USER_APP_HOOK }}
